name: "Damage Image - Deploy to Cloud Run"

on:
  workflow_dispatch:

jobs:
  setup-and-deploy:
    name: Damage Image - Deploy to Cloud Run
    runs-on: ubuntu-latest
    environment: prod

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Environment Variables
        run: |
          if [[ main == "${{ github.ref_name }}" ]]; then
            echo ENVIRONMENT=prd >> $GITHUB_ENV
            echo SERVICE_ACCOUNT=fulfilai-gha-485662822083@fulfilai-fulfillment-p-1-b6ad.iam.gserviceaccount.com>> $GITHUB_ENV
            echo WORKLOAD_IDENTITY_PROVIDER=projects/485662822083/locations/global/workloadIdentityPools/fulfilai-wkld-id-pool/providers/fulfilai-wkld-id-pool-provider >> $GITHUB_ENV
            echo DOCKER_IMAGE=us-east4-docker.pkg.dev/fulfilai-fulfillment-p-1-b6ad/fulfilai-docker-repository-use4/httpd-gar-img:latest >> $GITHUB_ENV
            echo VPC_CONNECTOR=projects/gcp-network-prodnet-p-3096/locations/us-east4/connectors/gcp-serverless-vpc-d-use4 >> $GITHUB_ENV

          else
            echo ENVIRONMENT=int >> $GITHUB_ENV
            echo SERVICE_ACCOUNT=fulfilai-gha-750864996575@fulfilai-fulfillment-d-1-5d7f.iam.gserviceaccount.com >> $GITHUB_ENV
            echo WORKLOAD_IDENTITY_PROVIDER=projects/750864996575/locations/global/workloadIdentityPools/fulfilai-wkldid-pool-d/providers/fulfilai-wkldid-pool-provider-d >> $GITHUB_ENV
            echo DOCKER_IMAGE=us-east4-docker.pkg.dev/fulfilai-fulfillment-d-1-5d7f/fulfilai-docker-repository-use4/httpd-gar-img:latest >> $GITHUB_ENV
            echo VPC_CONNECTOR=projects/gcp-network-devnet-p-0c1e/locations/us-east4/connectors/gcp-serverless-vpc-d-use4 >> $GITHUB_ENV

          fi

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy "damage-image-phase1-service" \
            --region "us-east4" \
            --image ${{ env.DOCKER_IMAGE }} \
            --ingress internal-and-cloud-load-balancing \
            --session-affinity \
            --vpc-egress "all" \
            --vpc-connector ${{ env.VPC_CONNECTOR }} \
            --port 8080 \
            --allow-unauthenticated \
            --memory 1Gi \
            --platform "managed" \
            --quiet


