name: "Build and Push Docker Image"

on:
  push:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  docker-build-and-push:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    environment: prod

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to google cloud
        uses: actions/checkout@v3

      - name: Set account env variables based on branch
        id: set-env
        run: |
          if [[ main == ${{ github.ref_name }} ]]; then
            echo ENVIRONMENT=prd >> $GITHUB_ENV
            echo SERVICE_ACCOUNT=fulfilai-gha-485662822083@fulfilai-fulfillment-p-1-b6ad.iam.gserviceaccount.com >> $GITHUB_ENV
            echo WORKLOAD_IDENTITY_PROVIDER=projects/485662822083/locations/global/workloadIdentityPools/fulfilai-wkld-id-pool/providers/fulfilai-wkld-id-pool-provider >> $GITHUB_ENV
          elif [[ develop == ${{ github.ref_name }} ]]; then
            echo ENVIRONMENT=int >> $GITHUB_ENV
            echo SERVICE_ACCOUNT=fulfilai-gha-750864996575@fulfilai-fulfillment-d-1-5d7f.iam.gserviceaccount.com >> $GITHUB_ENV
            echo WORKLOAD_IDENTITY_PROVIDER=projects/750864996575/locations/global/workloadIdentityPools/fulfilai-wkldid-pool-d/providers/fulfilai-wkldid-pool-provider-d >> $GITHUB_ENV
          fi

      - name: "Authenticate to Google Cloud"
        id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Get Environmental Variables
        run: |
          if [[ main == ${{ github.ref_name }} ]]; then
            echo DOCKER_TAGS=us-east4-docker.pkg.dev/fulfilai-fulfillment-p-1-b6ad/fulfilai-docker-repository-use4/httpd-gar-img:latest >> $GITHUB_ENV
          elif [[ develop == ${{ github.ref_name }} ]]; then
            echo DOCKER_TAGS=us-east4-docker.pkg.dev/fulfilai-fulfillment-d-1-5d7f/fulfilai-docker-repository-use4/httpd-gar-img:latest >> $GITHUB_ENV
          fi
      
    

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          registry: "us-east4-docker.pkg.dev"
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_TAGS }}

